
import jdk.nashorn.internal.parser.TokenType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
     String oprtr=new String();
     String val1=new String();
     String val2=new String();
    public calculator() {
        initComponents();
      oprtr="";
      val1="";
      val2="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btndec = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btnper = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnmul = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btneq = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton20.setBackground(new java.awt.Color(51, 102, 255));
        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("/");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btndec.setBackground(new java.awt.Color(255, 255, 255));
        btndec.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btndec.setText(".");
        btndec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btndiv.setBackground(new java.awt.Color(51, 102, 255));
        btndiv.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 255));
        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operators(evt);
            }
        });

        btnper.setBackground(new java.awt.Color(51, 102, 255));
        btnper.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnper.setForeground(new java.awt.Color(255, 255, 255));
        btnper.setText("%");
        btnper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operators(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 0, 255));
        jButton15.setText("C");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(51, 102, 255));
        btnsub.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnsub.setForeground(new java.awt.Color(255, 255, 255));
        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operators(evt);
            }
        });

        btnmul.setBackground(new java.awt.Color(51, 102, 255));
        btnmul.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnmul.setForeground(new java.awt.Color(255, 255, 255));
        btnmul.setText("*");
        btnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operators(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(51, 102, 255));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operators(evt);
            }
        });

        btneq.setBackground(new java.awt.Color(51, 102, 255));
        btneq.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btneq.setForeground(new java.awt.Color(255, 255, 255));
        btneq.setText("=");
        btneq.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        btneq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneqActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(btnper, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btndec, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(btneq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnper, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndec, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btneq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(!(val1.equals(""))&&oprtr.equals("")&&val2.equals(""))
           val1=val1.substring(0,val1.length()-1);
       else if(!(val1.equals(""))&&!(oprtr.equals(""))&&val2.equals(""))
            oprtr=oprtr.substring(0,oprtr.length()-1);
      else if(!(val1.equals(""))&&!(oprtr.equals(""))&&!(val2.equals("")))
      {
          val2=val2.substring(0,val2.length()-1);

       float a,b,c=0;
            a=Float.parseFloat(val1);
            b=Float.parseFloat(val2);
            if(oprtr.equals("+"))
                c=a+b;
            else if(oprtr.equals("*"))
                c=a*b;
            else if(oprtr.equals("-"))
                c=a-b;
            else if(oprtr.equals("%"))
                c=(a*b)/100;
            else if(oprtr.equals("/"))
                c=a/b;
             float t=c-(int)c;   
            if(t==0.0f)
            {
                 jLabel2.setText(Integer.toString((int)(c)));
            }
            else
            jLabel2.setText(Float.toString(c));
            }
              jLabel1.setText(val1+oprtr+val2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         jLabel1.setText("");
         oprtr="";
         val1="";
         val2="";
          jLabel2.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void operators(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operators
        // TODO add your handling code here:
        if(oprtr.equals("")&&val1.equals(""))
        {
            if(evt.getSource()==btnsub)
                val1=val1+"-";
        }
        else if(oprtr.equals(""))
        {
            if(evt.getSource()==btnadd)
                oprtr="+";
            else if(evt.getSource()==btnsub)
                oprtr="-";
            else if(evt.getSource()==btndiv)
                oprtr="/";
            else if(evt.getSource()==btnmul)
                oprtr="*";
            else
                oprtr="%";
        }
        else if(!(oprtr.equals(""))&&val2.equals(""))
        {
            if(evt.getSource()==btnsub)
                val2=val2+"-";
            else
            {
                 if(evt.getSource()==btnadd)
                oprtr="+";
            else if(evt.getSource()==btndiv)
                oprtr="/";
            else if(evt.getSource()==btnmul)
                oprtr="*";
            else
                oprtr="%";
            }
        }
         else if(!(oprtr.equals("")))
        {
            float a,b,c=0;
            a=Float.parseFloat(val1);
            b=Float.parseFloat(val2);
            if(oprtr.equals("+"))
                c=a+b;
            else if(oprtr.equals("*"))
                c=a*b;
            else if(oprtr.equals("-"))
                c=a-b;
            else if(oprtr.equals("%"))
                c=(a*b)/100;
            else if(oprtr.equals("/"))
                c=a/b;
            float t=c-(int)c;   
            if(t==0.0f)
            {
                 jLabel2.setText(Integer.toString((int)(c)));
            }
            else
            jLabel2.setText(Float.toString(c));
            val1=Integer.toString((int)(c));
            val2="";
            if(evt.getSource()==btnadd)
                oprtr="+";
            else if(evt.getSource()==btnsub)
                oprtr="-";
            else if(evt.getSource()==btndiv)
                oprtr="/";
            else if(evt.getSource()==btnmul)
                oprtr="*";
            else
                oprtr="%";
        }   
         jLabel1.setText(val1+oprtr+val2);
    }//GEN-LAST:event_operators

    private void buttons(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons
        // TODO add your handling code here:
       if(oprtr.equals(""))
       {
           if(evt.getSource()==btn0)
               val1=val1+"0";
           else if(evt.getSource()==btn1)
               val1=val1+"1";
           else if(evt.getSource()==btn2)
               val1=val1+"2";
           else if(evt.getSource()==btn3)
               val1=val1+"3";
           else if(evt.getSource()==btn4)
               val1=val1+"4";
           else if(evt.getSource()==btn5)
               val1=val1+"5";
           else if(evt.getSource()==btn6)
               val1=val1+"6";
           else if(evt.getSource()==btn7)
               val1=val1+"7";
           else if(evt.getSource()==btn8)
               val1=val1+"8";
           else if(evt.getSource()==btn9)
               val1=val1+"9";
           else 
               val1=val1+".";   
       }
       else
       {
              if(evt.getSource()==btn0)
               val2=val2+"0";
           else if(evt.getSource()==btn1)
               val2=val2+"1";
           else if(evt.getSource()==btn2)
               val2=val2+"2";
           else if(evt.getSource()==btn3)
               val2=val2+"3";
           else if(evt.getSource()==btn4)
               val2=val2+"4";
           else if(evt.getSource()==btn5)
               val2=val2+"5";
           else if(evt.getSource()==btn6)
               val2=val2+"6";
           else if(evt.getSource()==btn7)
               val2=val2+"7";
           else if(evt.getSource()==btn8)
               val2=val2+"8";
           else if(evt.getSource()==btn9)
               val2=val2+"9";
           else 
               val2=val2+".";   
              float a,b,c=0;
            a=Float.parseFloat(val1);
            b=Float.parseFloat(val2);
            if(oprtr.equals("+"))
                c=a+b;
            else if(oprtr.equals("*"))
                c=a*b;
            else if(oprtr.equals("-"))
                c=a-b;
            else if(oprtr.equals("%"))
                c=(a*b)/100;
            else if(oprtr.equals("/"))
                c=a/b;
             float t=c-(int)c;   
            if(t==0.0f)
            {
                 jLabel2.setText(Integer.toString((int)(c)));
            }
            else
            jLabel2.setText(Float.toString(c));
       }
       jLabel1.setText(val1+oprtr+val2);
    }//GEN-LAST:event_buttons

    private void btneqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneqActionPerformed
        // TODO add your handling code here:
         float a,b,c=0;
        if(val1.equals(""))
        {
            
        }
        else if(oprtr.equals(""))
        {
            jLabel1.setText(val1);
        }
        else if(val2.equals("")&&oprtr.equals("%"))
        {
            a=Float.parseFloat(val1);
            a=a/100;
             float t=a-(int)a;   
            if(t==0.0f)
            {
                 jLabel1.setText(Integer.toString((int)(a)));
            }
            else
            jLabel1.setText(Float.toString(a));
        }
      else
        {
            try {
                 a=Float.parseFloat(val1);
            b=Float.parseFloat(val2);
            if(oprtr.equals("+"))
                c=a+b;
            else if(oprtr.equals("*"))
                c=a*b;
            else if(oprtr.equals("-"))
                c=a-b;
            else if(oprtr.equals("%"))
                c=(a*b)/100;
            else if(oprtr.equals("/"))
                c=a/b;
            float t=c-(int)c;   
            if(t==0.0f)
            {
                 jLabel1.setText(Integer.toString((int)(c)));
            }
            else
            jLabel1.setText(Float.toString(c));
            } catch (Exception e) {
                jLabel1.setText("ERROR");
            }
           
        }
           val1="";
                oprtr="";
                val2="";
             jLabel2.setText("");
    }//GEN-LAST:event_btneqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndec;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btneq;
    private javax.swing.JButton btnmul;
    private javax.swing.JButton btnper;
    private javax.swing.JButton btnsub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
