/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form tictactoe
     */
    static int count=1;
    public tictactoe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC TAC TOE");

        btn1.setBackground(new java.awt.Color(255, 204, 0));
        btn1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 0));
        jButton5.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 0));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 0));
        jButton7.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 204, 0));
        jButton8.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 0));
        jButton9.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtn(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLAYER 1: YOUR TURN");
        jLabel1.setOpaque(true);

        jButton1.setText("CLICK TO REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickbtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickbtn
        // TODO add your handling code here:
       if(count%2==0)
       {
           if(evt.getSource()==btn1)
           {
               btn1.setText("O");
               btn1.setEnabled(false);
           }
           else if(evt.getSource()==jButton2)
           {
               jButton2.setText("O");
               jButton2.setEnabled(false);
           }
            else if(evt.getSource()==jButton3)
           {
               jButton3.setText("O");
               jButton3.setEnabled(false);
           }
            else if(evt.getSource()==jButton4)
           {
               jButton4.setText("O");
               jButton4.setEnabled(false);
           }
            else if(evt.getSource()==jButton5)
           {
               jButton5.setText("O");
               jButton5.setEnabled(false);
           }
           else if(evt.getSource()==jButton6)
           {
               jButton6.setText("O");
               jButton6.setEnabled(false);
           }
           else if(evt.getSource()==jButton7)
           {
               jButton7.setText("O");
               jButton7.setEnabled(false);
           }
           else if(evt.getSource()==jButton8)
           {
               jButton8.setText("O");
               jButton8.setEnabled(false);
           }
           else
           {
               jButton9.setText("O");
               jButton9.setEnabled(false);
           }
           jLabel1.setText("PLAYER 1: YOUR TURN");
       }
       else
       {
           if(evt.getSource()==btn1)
           {
               btn1.setText("X");
               btn1.setEnabled(false);
           }
           else if(evt.getSource()==jButton2)
           {
               jButton2.setText("X");
               jButton2.setEnabled(false);
           }
            else if(evt.getSource()==jButton3)
           {
               jButton3.setText("X");
               jButton3.setEnabled(false);
           }
            else if(evt.getSource()==jButton4)
           {
               jButton4.setText("X");
               jButton4.setEnabled(false);
           }
            else if(evt.getSource()==jButton5)
           {
               jButton5.setText("X");
               jButton5.setEnabled(false);
           }
           else if(evt.getSource()==jButton6)
           {
               jButton6.setText("X");
               jButton6.setEnabled(false);
           }
           else if(evt.getSource()==jButton7)
           {
               jButton7.setText("X");
               jButton7.setEnabled(false);
           }
           else if(evt.getSource()==jButton8)
           {
               jButton8.setText("X");
               jButton8.setEnabled(false);
           }
           else
           {
               jButton9.setText("X");
               jButton9.setEnabled(false);
           }
           jLabel1.setText("PLAYER 2: YOUR TURN");
       }
       if(count<=9)
       {
           if((btn1.getText()=="X"&&jButton4.getText()=="X"&&jButton7.getText()=="X")||(jButton2.getText()=="X"&&jButton5.getText()=="X"&&jButton8.getText()=="X")||(jButton3.getText()=="X"&&jButton6.getText()=="X"&&jButton9.getText()=="X")||(jButton2.getText()=="X"&&btn1.getText()=="X"&&jButton3.getText()=="X")||(jButton4.getText()=="X"&&jButton5.getText()=="X"&&jButton6.getText()=="X")||(jButton8.getText()=="X"&&jButton7.getText()=="X"&&jButton9.getText()=="X")||(jButton3.getText()=="X"&&jButton5.getText()=="X"&&jButton7.getText()=="X")||(btn1.getText()=="X"&&jButton5.getText()=="X"&&jButton9.getText()=="X"))
           {
               jLabel1.setText("PLAYER 1 WINS");
               btn1.setEnabled(false);
               jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                 jButton5.setEnabled(false);
                  jButton2.setEnabled(false);
                   jButton7.setEnabled(false);
                    jButton6.setEnabled(false);
                     jButton8.setEnabled(false);
                      jButton9.setEnabled(false);
                      
           }
           else if((btn1.getText()=="O"&&jButton4.getText()=="O"&&jButton7.getText()=="O")||(jButton2.getText()=="O"&&jButton5.getText()=="O"&&jButton8.getText()=="O")||(jButton3.getText()=="O"&&jButton6.getText()=="O"&&jButton9.getText()=="O")||(jButton2.getText()=="O"&&btn1.getText()=="O"&&jButton3.getText()=="O")||(jButton4.getText()=="O"&&jButton5.getText()=="O"&&jButton6.getText()=="O")||(jButton8.getText()=="O"&&jButton7.getText()=="O"&&jButton9.getText()=="O")||(jButton3.getText()=="O"&&jButton5.getText()=="O"&&jButton7.getText()=="O")||(btn1.getText()=="O"&&jButton5.getText()=="O"&&jButton9.getText()=="O"))
           {
               jLabel1.setText("PLAYER 2 WINS");
            btn1.setEnabled(false);
               jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                 jButton5.setEnabled(false);
                  jButton2.setEnabled(false);
                   jButton7.setEnabled(false);
                    jButton6.setEnabled(false);
                     jButton8.setEnabled(false);
                      jButton9.setEnabled(false);
           }
           else if(count==9)
           jLabel1.setText("DRAW");
       }
       count++;
       
    }//GEN-LAST:event_clickbtn

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        count=1;
        btn1.setText("");
        btn1.setEnabled(true);
        jButton2.setText("");
        jButton2.setEnabled(true);
         jButton3.setText("");
        jButton3.setEnabled(true);
         jButton4.setText("");
        jButton4.setEnabled(true);
         jButton5.setText("");
        jButton5.setEnabled(true);
         jButton6.setText("");
        jButton6.setEnabled(true);
         jButton7.setText("");
        jButton7.setEnabled(true);
         jButton8.setText("");
        jButton8.setEnabled(true);
         jButton9.setText("");
        jButton9.setEnabled(true);
        jLabel1.setText("PLAYER 1: YOUR TURN");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
